site_name: { { cookiecutter.friendly_name } }
docs_dir: "docs/"
repo_url: https://github.com/{{cookiecutter.github_user}}/{{cookiecutter.project_name}}
watch: [src/, docs/]
edit_uri: "blob/main/docs/"
theme:
  name: material
  favicon: _static/logo.png
  logo: _static/logo.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - toc.follow
  palette:
    primary: white
    accent: light blue

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

copyright: Copyright &copy; {{cookiecutter.copyright_year}} {{cookiecutter.author}}

nav:
  - Package:
      - Overview: index.md
      - Installation: installation.md
      - tutorials.md
  - API:
      - api.md

plugins:
  - mkdocs-jupyter
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          type: python
          root_package: { { cookiecutter.package_name } }
          docstring_style: google
          options:
            heading_level: 3
            show_source: true
            show_root_heading: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/{{cookiecutter.github_user}}/{{cookiecutter.project_name}}
