name: Cruft Check

on:
  pull_request:
    branches:
      - main

jobs:
  cruft-check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Cruft
        run: pip install cruft

      - name: Run Cruft Check
        id: cruft_check
        run: |
          if cruft check; then
            echo "Cruft check passed"
            echo "cruft_failed=0" >> $GITHUB_OUTPUT
          else
            echo "Cruft check failed"
            echo "cruft_failed=1" >> $GITHUB_OUTPUT
            exit 0
          fi

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: ✨ There is a newer version of continuous integration files or other tooling available ✨
          continue-on-error: true
