# creates the documentation on pushes it to the gh-pages branch
name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          make install

      - name: Build documentation
        shell: bash
        run: |
          make docs

      - name: Deploy documentation
        shell: bash
        run: |
          git config --global user.name "Documentation Bot"
          git config --global user.email "Documentation@bot.com"

          # push 'site' folder to gh-pages branch
          
          # Assuming the documentation is built in the 'site' directory
          cd site
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "Update documentation"

          # Push to the gh-pages branch
          git push --force ${{ secrets.GITHUB_TOKEN }} gh-pages