# THIS ACTION WILL:
  # creates the documentation on
  #  pushes it to the gh-pages branch
# SETUP:
  # to enable this PR:
    # go to the settings of the repository
    # go to the Pages menu item
    # for source select "deploy from a branch"
    # for branch select "gh-pages" (you might need to create the branch first)
# NOTES:
  # This is specific for the mkdocs-material theme, if you use another package for documentation, you will need to fix this action

name: Documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]


permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
  
      - name: Dependencies
        run: |
          make install

      - name: Build and Deploy
        if: github.event_name == 'push'
        run: mkdocs gh-deploy --force
      
      - name: Build
        if: github.event_name == 'pull_request'
        run: make build-docs