# GitHub action to check if pre-commit has been run. Runs from .pre-commit-config.yaml, where the pre-commit actions are.

name: run-pre-commit

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pre-commit:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PRE_COMMIT }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Install pre-push hooks
        run: pre-commit install --install-hooks -t pre-push

      - name: Run pre-commit
        id: pre_commit
        continue-on-error: true
        run: |
          if pre-commit run --hook-stage push --all-files; then
            echo "Pre-commit check passed"
            echo "pre_commit_failed=0" >> $GITHUB_OUTPUT
          else
            echo "Pre-commit check failed"
            echo "pre_commit_failed=1" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Commit formatting
        if: ${{ steps.pre_commit.outputs.pre_commit_failed == 1 && github.event_name == 'pull_request' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "style: linting"
          git push

      - uses: mshick/add-pr-comment@v2
        if: ${{ steps.pre_commit.outputs.pre_commit_failed == 1 && github.event_name == 'pull_request' }}
        id: add_comment
        with:
          message: |
            ✨ Looks like some pre-commit hooks failed. Those that could be automatically fixed have been comitted to the branch. ✨
            
            We suggest using `git pull --rebase` to apply them locally

            If any failed due to other causes, you can fix it locally by running `pre-commit run --hook-stage push --all-files`

      - name: Fail workflow
        if: ${{ steps.pre_commit.outputs.pre_commit_failed == 1 && github.event_name == 'pull_request' }}
        run: exit 1
