name: Create a cruft project

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-for-rej-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cruft create
        run: |
          cruft create . -y 
          cd swift-python
          chmod +x .github/first_setup.sh
          bash .github/first_setup.sh
