name: Test creating an instance of the template

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  create-template-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git user information
        run: |
          git config --global user.name "Test"
          git config --global user.email "test@gmail.com"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Cruft create
        run: |
          # Using a bash script allows testing locally as well
          chmod +x test_template_creation.sh
          ./test_template_creation.sh
