name: Test creating an instance of the template

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  create-template-instance:
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.workflow }} @ ${{ github.ref }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git user information
        run: |
          git config --global user.name "Test"
          git config --global user.email "test@gmail.com"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Cruft create
        run: |
          # Using invoke allows testing locally as well
          pip install invoke
          inv test-instantiation
