name: Test creating an instance of the template

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-for-rej-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    - name: Set Git user information
      run: |
        git config --global user.name "MartinBernstorff"
        git config --global user.email "martinbernstorff@gmail.com"

      - name: Cruft create
        run: |
          # Using a bash script allows testing locally as well
          chmod +x test_template_creation.sh
          ./test_template_creation.sh
