name: Test creating an instance of the template

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  create-template-instance:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9"] # , "3.10"]
    
    runs-on: ${{ matrix.os }}
        
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git user information
        run: |
          git config --global user.name "Test"
          git config --global user.email "test@gmail.com"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
  
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cruft create
        run: |
          make test